name: 'Config pages'
type: module
description: 'Allows the creation of custom configuration entities.'
package: Entity
# version: 0.01
# core: 8.x
dependencies:
  - text
configure: entity.config_pages.collection

# Information added by Drupal.org packaging script on 2016-07-22
version: '8.x-1.0-rc5'
core: '8.x'
project: 'config_pages'
datestamp: 1469212140
