view config_pages entity:
  title: 'View ConfigPages entity'
  description: 'Allow view ConfigPages'

edit config_pages entity:
  title: 'Edit ConfigPages entity'
  description: 'Allow edit ConfigPages'

delete config_pages entity:
  title: 'Delete ConfigPages entity'
  description: 'Allow delete ConfigPages'

administer config_pages types:
  title: 'Administer Config Pages'
  description: 'Create and delete fields for Config Pages.'
